version: "3"

services:
  app:
    image: piedit:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/:/root
    network_mode: host

